### PR TITLE
CB-14178: Improved README

### PR DESCRIPTION
**Pull request by erisu**
### What does this PR do?
- Fixes the `cordova-plugin-camera` broken link.
- Fixes badges that links only to the badge image and not the build status.
- Added missing badges to show test results and coverage.
- Re-order the **Core Plugin** section and added Code Coverage column to be consistent with the other sections.
- Updated AppVeyor's badge image links to be a consistent format and to display only last master results

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.

### CODE REVIEW

**Comment by erisu** [comment]
I noticed that some of the project's AppVeyor build results appear to be on Humbedooh account while the others are on ApacheSoftwareFoundation.

While these projects are on Humbedooh, it also appears to exist on ApacheSoftwareFoundation but from the GitHub repo, it links back to Humbedooh.  I am not sure if it is necessary to take any action, but I left them as Humbedooh in the README to be consistent with the link from GitHub.

- https://ci.appveyor.com/project/Humbedooh/cordova-ios/branch/master
- https://ci.appveyor.com/project/Humbedooh/cordova-android/branch/master
- https://ci.appveyor.com/project/Humbedooh/cordova-windows/branch/master
- https://ci.appveyor.com/project/Humbedooh/cordova-js/branch/master
- https://ci.appveyor.com/project/Humbedooh/cordova-lib/branch/master

**Comment by janpio** [comment]
(Cleaning up the AppVeyor situation would be awesome... Same stuff tripped me up the last time I had to jump into those.)

**Review by raphinesse — APPROVED** [review]
LGTM. Thanks a lot for your work!

Regarding the different AppVeyor accounts: we will have to figure out the situation with the Apache infrastructure team first. So I think we should leave it as is for now.

**Comment by raphinesse** [comment]
@janpio Do we have to take extra steps to publish the updated status page after merging this?

**Comment by janpio** [comment]
Good question, I have no idea. The README contains some instructions, but those are clearly outdated as the links don't work.

@shazron, @alsorokin ?

**Comment by erisu** [comment]
@janpio @raphinesse 

From digging around, it seems that GitHub used to have a button called `Automatic Page Generator` but has been removed since. 

It appears that the GH page configuration has been migrated to [repo settings](https://github.com/apache/cordova-status/settings). 

I suspect the new steps would be:
- Go to GitHub Pages settings located in [repo settings](https://github.com/apache/cordova-status/settings)
- Select Source. 
  - I believe we currently use `gh-page` branch
- Change Theme
- Select `Modernist` from the preview
- Click `Select Theme`

I also believe that these steps are a one-time setup so we might not need to maintain the step in README. In my forked repo, I set up a GH page for testing and saw no option to updating or publishing changes. It appears to use the contents from README.md as the index/landing page.

I wonder if the source branch could be moved to master so on every merge, the site is updated automatically. From the test, I only see one extra file being written to the branch. `_config.yml`

**Comment by shazron** [comment]
@erisu Since we don't have access to the Settings page, we might need to ask INFRA to do it for us. If you could file an issue that would be great! https://issues.apache.org/jira/projects/INFRA

**Pull request merged**
