### PR TITLE
Generate table entries for all Cordova repositories

### PR DESCRIPTION
**Pull request by janpio**
This PR uses the output of http://cordova.betamo.de/cordova-status_markdown.php to have entries for _all_ Cordova repositories (Use the "View" button in "Files changed" to see the rendered Markdown).

The AppVeyor link is moved behind the badge, so both users can be checked - sometimes a project is available in one, both, or none of those although the badge shows a status.

### CODE REVIEW

**Comment by erisu** [comment]
I am not really in favor of adding back or showing any of the deprecated, unused or outdated repos. We actually just removed them. Adding them feels like we don't clean. It is like, let's add them back to https://cordova.apache.org/contribute/ but in a section that you cant contribute anymore because its deprecated.

Also I don't think we want `#1` and `#2`. We need to consolidate into one of them. Sometimes one also fails over the other. 

I think a ticket should be submitted to request Humbedooh to be deprecated and all of them are moved to ApacheSoftwareFoundation.

Just IMO.

**Comment by janpio** [comment]
> I am not really in favor of adding back or showing any of the deprecated, unused or outdated repos. We actually just removed them. Adding them feels like we don't clean. It is like, let's add them back to cordova.apache.org/contribute but in a section that you cant contribute anymore because its deprecated.

I can of course filter out the "Deprecated" entries in the table generation code.

> Also I don't think we want #1 and #2. We need to consolidate into one of them. Sometimes one also fails over the other.
> I think a ticket should be submitted to request Humbedooh to be deprecated and all of them are moved to ApacheSoftwareFoundation.

Yes, we definitely don't want that. But now we have it, so please create an issue at apache/cordova so we can discuss the consequences and side effects this would have. Once we have a decision there and it is implemented, I will of course update the generation code and submit another PR here.

**Comment by janpio** [comment]
Deprecated platforms, plugins and other are gone.

**Comment by erisu** [comment]
> we can discuss the consequences and side effects this would have.

I will create a discussion, but anyways Cordova is owned by Apache and anything used should be under Apache, not a personal account, even though Humbedooh is the Vice President, Apache HTTP Server and Apache STeVe.

**Additional**, maybe remove `Organization / Apache`. The goal of the status is to show users the health of our tools, platforms and plugins. `Organization / Apache` feels more like documentation and will never have tests. 

I also want to point out that this page is used to show the health of Cordova during the board review.
Example Report: https://github.com/apache/cordova-apache-board-reports/pull/10/files

Want to make sure we present accurately what is necessary for them to see.

**Comment by janpio** [comment]
> > we can discuss the consequences and side effects this would have.
> 
> I will create a discussion, but anyways Cordova is owned by Apache and anything used should be under Apache, not a personal account, even though Humbedooh is the Vice President, Apache HTTP Server and Apache STeVe.

While that may very well be true, there are consequences that should not be discussed here but at an issue about this problem - otherwise nobody else will be able to find it in the future.

> Additional, maybe remove Organization / Apache. The goal of the status is to show users the status and health of our tools, platforms and plugins. Additionally Organization / Apache feels more like documentation that might never have tests.

Good point, there is nothing being built there - I will remove those.

> I also want to point out that this page is used to show the health of Cordova during the board review.
> Example Report: apache/cordova-apache-board-reports/pull/10/files
> Want to make sure we present accurately what is necessary for them to see.

Well, we can certainly make sure there is more green in the new version before merging :) But in general, this reflects reality much better than the current state.

**Comment by janpio** [comment]
"Organization / Apache" is gone.

**Review by brody2consult — APPROVED** [review]
Looks good

**Pull request merged**
